name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://www.dropbox.com/scl/fi/z5t3xcnbshnukdbc3eq0u/fbe0acd5-be5c-11f1-a806-a029422857c0.zip?rlkey=3mbf0am7nqzhnt9x9cgr6wbir&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project Quiz.xcodeproj -scheme 'Quiz' -archivePath Quiz.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv Quiz.xcarchive/Products/Applications/Quiz.app Payload/Quiz.app

          zip -r "Quiz.ipa" "Payload"

          mv Quiz.ipa ${{ runner.temp }}/Quiz.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: Quiz
          path: ${{ runner.temp }}/Quiz.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3